### ISSUE TITLE
表格优化问题

### ISSUE THREAD

**Issue by GeXyu** [huangxd-/hugo#1]
目前表格边界不清晰，希望增加表格的优化
--------------------------------------------
目前表格效果如下：
![image](https://user-images.githubusercontent.com/17961307/116022828-8789a600-a67d-11eb-970c-661c98d8f2e2.png)

**Comment by huangxd-** [comment]
![image](https://user-images.githubusercontent.com/1921036/116696917-14718e00-a9f5-11eb-8308-5387a39169df.png)
已更新表格样式 @GeXyu
